### ISSUE TITLE
Some wrong setting link texts 

### ISSUE THREAD

**Issue by sirainen** [dovecot/documentation#1008]
These setting links try to link to a setting with a specific text, but intead they end up having "setting name = text" while only "text" was intended. Is there a way to fix these?

```
docs/core/admin/guides/spam_reporting.md:[[setting,sieve_&gt;extension&lt;_bin_dir,sieve_pipe_bin_dir]]. You
docs/core/config/auth/userdb.md:[[setting,namespace/separator,namespace/default/separator]] extra field.
docs/installation/upgrade/include/2.3-to-2.3.x.inc:  [[setting,namespace/mailbox/auto,mailbox { auto }]] instead.
docs/installation/upgrade/include/2.3-to-2.3.x.inc:  [[setting,namespace/mailbox/autoexpunge,mailbox { autoexpunge }]] instead.
```
And in Pro docs:

```
docs/plugins/virtual_attachments.md:[[setting,namespace/mailbox/auto,auto-created]].
```

**Comment by slusarz** [comment]
That's currently the expected behavior.  See https://github.com/dovecot/documentation/tree/main?tab=readme-ov-file#settings

**Comment by sirainen** [comment]
Yeah, expected perhaps, but not wanted behavior in these cases, since it just looks wrong. Could we maybe add 4th parameter like `[[setting,key,,text]]` and it just creates a link to `key` with `text` as the link.

**Comment by slusarz** [comment]
That's probably the only way of doing it.  I was thinking of maybe creating a separate markdown link item that is essentially an alias of setting, that would have different output display semantics, but that's probably even more confusing.

**Comment by slusarz** [comment]
Added `setting_text` markdown command to handle the situation where you want link to be specific text.
