### ISSUE TITLE
No information about config files

### ISSUE THREAD

**Issue by grumagargler** [dovecot/documentation#157]
Dovecot server comes with many configuration files. Unfortunately, current documentation doesn't describe any of them. Practically, it means that I see _what_ I can configure but have no clue _how_.
Can you please improve the documentation adding to it such important information.
Thank you.

**Comment by cmouse** [comment]
All of the files in conf.d/ directory which end with .conf get merged into single file during config read. There is no particular file you should be using.

**Comment by grumagargler** [comment]
Thank you!

> All of the files in conf.d/ directory which end with .conf get merged into single file during config read. There is no particular file you should be using.

It would be very helpful (for me at least) to have such hint somewhere in https://doc.dovecot.org/settings/. I understand this is obvious for experienced admins but such approach isn't applied everywhere (for instance, postifix config files (main and master) have even different formats).

**Comment by cmouse** [comment]
We'll see what can be done to address this.
