### ISSUE TITLE
Missing Warning on Procmail

### ISSUE THREAD

**Issue by technojoe** [dovecot/documentation#267]
This warning should be at the top of https://wiki.dovecot.org/procmail :
"Procmail's last release was September 10, 2001. It is no longer maintained, and it has a number of security vulnerabilities. Consider using Sieve filtering in Dovecot Pigeonhole instead."

I was unable to add it to the wiki entry. Could it be added?

Thanks.

**Comment by cmouse** [comment]
Hi!

We are moving pages from wiki.dovecot.org to doc.dovecot.org. We can add such warning when we move it.
