### ISSUE TITLE
add existing protocol "submissions" (submission-tls) on port 465 to docs

### ISSUE THREAD

**Issue by sh-dvl** [dovecot/documentation#375]
we're just moving some services and searched dovecot-docs for submission via ssl (without starttls).

only in sourcecode we've found, that there's already an entry "submissions" via port 465 .

please note this somewhere in online-docs or perhaps better in default-config.

**Comment by cmouse** [comment]
Thanks, we'll consider adding it.

**Comment by cmouse** [comment]
Closing with https://github.com/dovecot/core/commit/7409bc25438ad5123c3b81c742ada779c173d28b
