### ISSUE TITLE
Add example for illustration of keyword in dovecot-virtual

### ISSUE THREAD

**Issue by ma-ef** [dovecot/documentation#547]
I suggest to add another example for dovecot-virtual in https://doc.dovecot.org/configuration_manual/virtual_plugin/#examples

List all emails that have been tagged with 'To Do' using Thunderbird as an email client (Thunderbird uses '$label4' as IMAP keyword for the 'To Do' tag):
```
*
  KEYWORD $label4
```

**Comment by cmouse** [comment]
Hi! Thanks for the feedback, would it be possible for you to make the pull request?
