### ISSUE TITLE
Clarify that using Dovecot SASL to authenticate postfix only works if Dovecot is operating as a backend, not a proxy

### ISSUE THREAD

**Issue by jmcclelland** [dovecot/documentation#554]
There's a clear and concise [documentation page](https://doc.dovecot.org/configuration_manual/howto/postfix_and_dovecot_sasl/) explaining how you can use Dovecot SASL to authenticate postfix users.

However, if you setup Postfix and Dovecot in this manner _and Dovecot is configured as a proxy_, it fails open. In other words, Dovecot will allow any user to relay email provided they have a correct username, regardless of the password they enter.

I found an [old reference](https://dovecot.dovecot.narkive.com/eRrxOaJ3/postfix-sasl-auth-using-with-password-forwarding-proxy-configuration#post8) to this fact, but it would be nice if this problem were clearly stated in the docs, especially given the security implications.

**Comment by cmouse** [comment]
This only happens if you misconfigure dovecot as a proxy. You should authenticate users on the proxy level already.

**Comment by jmcclelland** [comment]
If this is not the expected behavior then perhaps this ticket can be closed and I should raise this in a Dovecot users forum or as a Dovecot bug (in my case, the Dovecot proxy authenticates IMAP/POP access properly, but postfix access is granted with any password provided a configured username is passed).

**Comment by cmouse** [comment]
That sounds like a bug. Can you please mail to dovecot@dovecot.org with doveconf -n and other related logs and we can continue this there. Thanks!
