### ISSUE TITLE
HA Proxy Configuration Manual not updated on doc.dovecot.org

### ISSUE THREAD

**Issue by thisgitisnotcommit** [dovecot/documentation#762]
The following files have not been updated on the website since November. 
I did not see a release schedule. Not sure if this is normal.

source/configuration_manual/haproxy/index.rst

**Comment by cmouse** [comment]
Totally normal. You can see recent commits in history.

**Comment by cmouse** [comment]
also why haproxy manual in particular?

**Comment by cmouse** [comment]
So no issue here, after all?
