### ISSUE TITLE
Broken link in /etc/dovecot/dovecot.conf

### ISSUE THREAD

**Issue by lane-ftw** [dovecot/documentation#838]
```
## Dovecot configuration file
# If you're in a hurry, see http://wiki2.dovecot.org/QuickConfiguration
```

![Screenshot 2024-01-30 143305](https://github.com/dovecot/documentation/assets/80347498/2c9647bb-83fc-4a94-9825-bd9a97642b90)
If it matters, this was installed on alpine 3.19 using `apk add dovecot` dovecot 2.3.21

**Comment by slusarz** [comment]
`/etc/dovecot/dovecot.conf` is part of Dovecot core (https://github.com/dovecot/core) - issues with core components should be reported there.

Regardless, your installation seems to be very out of date.  This wiki reference (and others) was fixed almost 2 years ago: https://github.com/dovecot/core/commit/6654621a0ee1c787edf0236c37aeec5d5b314f36

**Comment by cmouse** [comment]
I'll add a redirect anyways...
