### ISSUE TITLE
removed dsync doc during replicator doc removal

### ISSUE THREAD

**Issue by qyanu** [dovecot/documentation#885]
Hallo,

in commit 9270dfbb7f4be1539219403a60bb4038db5a1195 the subpage ``configuration_manual/replication.html`` was removed from the documentation. According to the commit message this was due to the "replicator" feature being removed. That the *replicator* feature is removed is also listed in the doc subpage ``installation_guide/upgrading/from-2.3-to-3.0.html``.

I think this complete removal of the *replication* subpage was in error, as its content explained more about the inner workings of *doveadm sync* (previously named *dsync*) rather than *replicator*. The 2.3 to 3.0 migration notes in subpage ``installation_guide/upgrading/from-2.3-to-3.0.html`` still list ``doveadm sync`` as a non-removed feature, so i think the documentation should be non-removed as well.

best regards,

Max

**Comment by sirainen** [comment]
Are we looking at the same page? In the commit you referred to I see very little non-replication-specific content that was removed.

**Comment by slusarz** [comment]
Agreed with @sirainen : most everything in that page is about replication, which has been removed.

Arguably, there are a few things in that page around doveadm service configuration that could be put into a page somewhere.  But that's generic doveadm stuff, not anything to do with using the dsync command itself.

The dsync command is documented at https://doc.dovecot.org/3.0/man/doveadm-sync.1/ - any suggestions on what can be added there would be great.  But dsync, by definition, requires connecting to a remote server, so it is beyond the scope of Dovecot documentation to try to predict what configuration is needed to connect to that remote server.  That's no longer documenting Dovecot; that is moving into the territory of solutioning.

**Comment by qyanu** [comment]
If all the content regarding dsync now (only) resides in the manpages, then i would still say that some kind of howto-like page is missing. And...

- does the warning about shared-folder-replication still apply? (i don't have shared folders on my little private playground-server, but this warning sounds important to keep)
- I find it handy when a documentation provides step-by-step information like for example the section https://doc.dovecot.org/configuration_manual/replication/#dsync-over-tcp-connections
  > Create a listener for doveadm-server:
  > service doveadm {
  >   inet_listener {
  >     port = 12345
  >   }
  > }

  Not necessarily because then that's the only place where to get information from or in order to blindly follow the steps, but because then all the multiple configuration options from all the different manpages (doveadm service inet_listener port, doveadm client's ``doveadm_port``, etc) that are relevant are grouped together in one read.

PS: I noticed that the subpage https://doc.dovecot.org/configuration_manual/replication will be removed because i wanted to submit a tiny improvement via a pull-request:

sshd since v7.2 supports the ``restrict`` option in the authorized_keys file, which promises to be future-proof (and is shorter to write). the diff would be something like the following:

> /root/.ssh/authorized_keys:
> - command="/usr/local/bin/dsync-in-wrapper.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty <ssh key>
> + command="/usr/local/bin/dsync-in-wrapper.sh",restrict <ssh key>

**Comment by slusarz** [comment]
There doesn't seem to be anything actionable here.

As discussed above, there is no support for replication between Dovecot servers in 2.4 so there is no need to document any of this.

As for the addition to 2.3, if you want to submit an MR to release-2.3 branch, we will take a look.  Otherwise, we are not really touching 2.3 documentation ourselves (unless code changes), and replication is not in 2.4 so there is nothing to do with the actively maintained doc branch.
