### ISSUE TITLE
A little bug in page  https://doc.dovecot.org/configuration_manual/authentication/lua_based_authentication/#authentication-lua-based-authentication

### ISSUE THREAD

**Issue by donghj2000** [dovecot/documentation#897]
These two sections are repeating.

[Lua based authentication](https://doc.dovecot.org/configuration_manual/authentication/lua_based_authentication/#id4)
When used in authentication, additional module dovecot.auth is added, which contains constants for passdb and userdb.

For details about Dovecot Lua, see [Dovecot Lua Support](https://doc.dovecot.org/admin_manual/lua/#lua).

When used in authentication, additional module dovecot.auth is added, which contains constants for passdb and userdb.

**Comment by slusarz** [comment]
This is fixed in new documentation: https://doc.dovecot.org/main/core/config/auth/databases/lua.html#authentication
