### ISSUE TITLE
New events page has fields hidden by default

### ISSUE THREAD

**Issue by sirainen** [dovecot/documentation#995]
I have to click "fields" for every event I want to look at. This is rather tiresome, and prevents searching text from the page. How about expanding them all by default, or at least have a button to expand.

**Comment by slusarz** [comment]
@sirainen : is this better?

**Comment by cmouse** [comment]
is this now fixed?

**Comment by sirainen** [comment]
At least the output is ok by me.

**Comment by fleischie** [comment]
If the relevant comments on the MRs are handled, then they will close this issue.
